plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-90
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  brakeman:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
exclude_paths:
- spec/**/*
- vendor/**/*
