language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
before_script:
  - psql -c 'create database enju_biblio_dummy_test;' -U postgres
  - psql enju_biblio_dummy_test -c 'CREATE EXTENSION pgcrypto'
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: a4NQNeYYOKABDoP9lFJt9oEx6QRRfagA4sjOeJUMjdc2AFGDtZ95FvZom9s9YYimduIUQfUScNF4tJvAzqrYhHTAaBxcLRERZQZWse4sZj0+xzSvUqauPCXwDheVCc/tlriUm06skKfz8WZBqL6vZyw4FfV6xLSrHVFAeIeSdsU=
sudo: false
addons:
  postgresql: "9.6"
