language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_oai.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
  exclude:
  - gemfile: gemfiles/rails_4.2_oai.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.1.9
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.2.5
    gemfile: gemfiles/rails_3.2.gemfile
  include:
  - rvm: 2.2.5
    gemfile: gemfiles/rails_4.2_oai.gemfile
    env: DB=postgresql
notifications:
  slack:
    secure: a4NQNeYYOKABDoP9lFJt9oEx6QRRfagA4sjOeJUMjdc2AFGDtZ95FvZom9s9YYimduIUQfUScNF4tJvAzqrYhHTAaBxcLRERZQZWse4sZj0+xzSvUqauPCXwDheVCc/tlriUm06skKfz8WZBqL6vZyw4FfV6xLSrHVFAeIeSdsU=
sudo: false
