language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
before_script:
  - psql -c 'CREATE DATABASE enju_biblio_dummy_test; CREATE EXTENSION pgcrypto;'
  - bundle exec rake db:migrate
after_script:
  - bundle exec codeclimate-test-reporter
services:
  - elasticsearch
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: a4NQNeYYOKABDoP9lFJt9oEx6QRRfagA4sjOeJUMjdc2AFGDtZ95FvZom9s9YYimduIUQfUScNF4tJvAzqrYhHTAaBxcLRERZQZWse4sZj0+xzSvUqauPCXwDheVCc/tlriUm06skKfz8WZBqL6vZyw4FfV6xLSrHVFAeIeSdsU=
sudo: false
addons:
  postgresql: "9.4"
