language: ruby
cache: bundler
rvm:
  - 2.1.7
  - 2.2.3
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_oai.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
  - rvm: 2.1.7
  - rvm: 2.2.3
notifications:
  slack:
    secure: a4NQNeYYOKABDoP9lFJt9oEx6QRRfagA4sjOeJUMjdc2AFGDtZ95FvZom9s9YYimduIUQfUScNF4tJvAzqrYhHTAaBxcLRERZQZWse4sZj0+xzSvUqauPCXwDheVCc/tlriUm06skKfz8WZBqL6vZyw4FfV6xLSrHVFAeIeSdsU=
sudo: false
