 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/manifestation_custom_properties", type: :request do
  # ManifestationCustomProperty. As you add validations to ManifestationCustomProperty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ManifestationCustomProperty.create! valid_attributes
      get manifestation_custom_properties_url
      response.status.should redirect_to(new_user_session_url)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      manifestation_custom_property = ManifestationCustomProperty.create! valid_attributes
      get manifestation_custom_property_url(manifestation_custom_property)
      expect(response).to redirect_to(new_user_session_url)
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_manifestation_custom_property_url
      expect(response).to redirect_to(new_user_session_url)
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      manifestation_custom_property = ManifestationCustomProperty.create! valid_attributes
      get edit_manifestation_custom_property_url(manifestation_custom_property)
      expect(response).to redirect_to(new_user_session_url)
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ManifestationCustomProperty" do
        expect {
          post manifestation_custom_properties_url, params: { manifestation_custom_property: valid_attributes }
        }.to change(ManifestationCustomProperty, :count).by(1)
      end

      it "redirects to the created manifestation_custom_property" do
        post manifestation_custom_properties_url, params: { manifestation_custom_property: valid_attributes }
        expect(response).to redirect_to(manifestation_custom_property_url(ManifestationCustomProperty.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ManifestationCustomProperty" do
        expect {
          post manifestation_custom_properties_url, params: { manifestation_custom_property: invalid_attributes }
        }.to change(ManifestationCustomProperty, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post manifestation_custom_properties_url, params: { manifestation_custom_property: invalid_attributes }
        expect(response).to redirect_to(new_user_session_url)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manifestation_custom_property" do
        manifestation_custom_property = ManifestationCustomProperty.create! valid_attributes
        patch manifestation_custom_property_url(manifestation_custom_property), params: { manifestation_custom_property: new_attributes }
        manifestation_custom_property.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the manifestation_custom_property" do
        manifestation_custom_property = ManifestationCustomProperty.create! valid_attributes
        patch manifestation_custom_property_url(manifestation_custom_property), params: { manifestation_custom_property: new_attributes }
        manifestation_custom_property.reload
        expect(response).to redirect_to(manifestation_custom_property_url(manifestation_custom_property))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        manifestation_custom_property = ManifestationCustomProperty.create! valid_attributes
        patch manifestation_custom_property_url(manifestation_custom_property), params: { manifestation_custom_property: invalid_attributes }
        expect(response).to redirect_to(new_user_session_url)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested manifestation_custom_property" do
      manifestation_custom_property = ManifestationCustomProperty.create! valid_attributes
      expect {
        delete manifestation_custom_property_url(manifestation_custom_property)
      }.to change(ManifestationCustomProperty, :count).by(-1)
    end

    it "redirects to the manifestation_custom_properties list" do
      manifestation_custom_property = ManifestationCustomProperty.create! valid_attributes
      delete manifestation_custom_property_url(manifestation_custom_property)
      expect(response).to redirect_to(manifestation_custom_properties_url)
    end
  end
end
