require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResourceExportFilesController do
  fixtures :all

  # This should return the minimal set of attributes required to create a valid
  # ResourceExportFile. As you add validations to ResourceExportFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResourceExportFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    login_fixture_admin
    it "assigns all resource_export_files as @resource_export_files" do
      resource_export_file = ResourceExportFile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:resource_export_files).should eq([resource_export_file])
    end
  end

  describe "GET show" do
    login_fixture_admin
    it "assigns the requested resource_export_file as @resource_export_file" do
      resource_export_file = ResourceExportFile.create! valid_attributes
      get :show, {:id => resource_export_file.to_param}, valid_session
      assigns(:resource_export_file).should eq(resource_export_file)
    end
  end

  describe "GET new" do
    login_fixture_admin
    it "assigns a new resource_export_file as @resource_export_file" do
      get :new, {}, valid_session
      assigns(:resource_export_file).should be_a_new(ResourceExportFile)
    end
  end

  describe "GET edit" do
    login_fixture_admin
    it "assigns the requested resource_export_file as @resource_export_file" do
      resource_export_file = ResourceExportFile.create! valid_attributes
      get :edit, {:id => resource_export_file.to_param}, valid_session
      assigns(:resource_export_file).should eq(resource_export_file)
    end
  end

  describe "POST create" do
    login_fixture_admin
    describe "with valid params" do
      it "creates a new ResourceExportFile" do
        expect {
          post :create, {:resource_export_file => valid_attributes}, valid_session
        }.to change(ResourceExportFile, :count).by(1)
      end

      it "assigns a newly created resource_export_file as @resource_export_file" do
        post :create, {:resource_export_file => valid_attributes}, valid_session
        assigns(:resource_export_file).should be_a(ResourceExportFile)
        assigns(:resource_export_file).should be_persisted
      end

      it "redirects to the created resource_export_file" do
        post :create, {:resource_export_file => valid_attributes}, valid_session
        response.should redirect_to(ResourceExportFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved resource_export_file as @resource_export_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceExportFile.any_instance.stub(:save).and_return(false)
        post :create, {:resource_export_file => {  }}, valid_session
        assigns(:resource_export_file).should be_a_new(ResourceExportFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceExportFile.any_instance.stub(:save).and_return(false)
        post :create, {:resource_export_file => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    login_fixture_admin
    describe "with valid params" do
      it "updates the requested resource_export_file" do
        resource_export_file = ResourceExportFile.create! valid_attributes
        # Assuming there are no other resource_export_files in the database, this
        # specifies that the ResourceExportFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ResourceExportFile.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => resource_export_file.to_param, :resource_export_file => { "these" => "params" }}, valid_session
      end

      it "assigns the requested resource_export_file as @resource_export_file" do
        resource_export_file = ResourceExportFile.create! valid_attributes
        put :update, {:id => resource_export_file.to_param, :resource_export_file => valid_attributes}, valid_session
        assigns(:resource_export_file).should eq(resource_export_file)
      end

      it "redirects to the resource_export_file" do
        resource_export_file = ResourceExportFile.create! valid_attributes
        put :update, {:id => resource_export_file.to_param, :resource_export_file => valid_attributes}, valid_session
        response.should redirect_to(resource_export_file)
      end
    end

    describe "with invalid params" do
      it "assigns the resource_export_file as @resource_export_file" do
        resource_export_file = ResourceExportFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceExportFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => resource_export_file.to_param, :resource_export_file => {  }}, valid_session
        assigns(:resource_export_file).should eq(resource_export_file)
      end

      it "re-renders the 'edit' template" do
        resource_export_file = ResourceExportFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceExportFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => resource_export_file.to_param, :resource_export_file => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    login_fixture_admin
    it "destroys the requested resource_export_file" do
      resource_export_file = ResourceExportFile.create! valid_attributes
      expect {
        delete :destroy, {:id => resource_export_file.to_param}, valid_session
      }.to change(ResourceExportFile, :count).by(-1)
    end

    it "redirects to the resource_export_files list" do
      resource_export_file = ResourceExportFile.create! valid_attributes
      delete :destroy, {:id => resource_export_file.to_param}, valid_session
      response.should redirect_to(resource_export_files_url)
    end
  end

end
