require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SeriesStatementRelationshipsController do
  fixtures :users, :roles

  # This should return the minimal set of attributes required to create a valid
  # SeriesStatementRelationship. As you add validations to SeriesStatementRelationship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SeriesStatementRelationshipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    login_fixture_librarian

    it "assigns all series_statement_relationships as @series_statement_relationships" do
      series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
      get :index, {}, valid_session
      assigns(:series_statement_relationships).should eq([series_statement_relationship])
    end
  end

  describe "GET show" do
    login_fixture_librarian

    it "assigns the requested series_statement_relationship as @series_statement_relationship" do
      series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
      get :show, {:id => series_statement_relationship.to_param}, valid_session
      assigns(:series_statement_relationship).should eq(series_statement_relationship)
    end
  end

  describe "GET new" do
    login_fixture_librarian

    it "assigns a new series_statement_relationship as @series_statement_relationship" do
      get :new, {}, valid_session
      assigns(:series_statement_relationship).should be_a_new(SeriesStatementRelationship)
    end
  end

  describe "GET edit" do
    login_fixture_librarian

    it "assigns the requested series_statement_relationship as @series_statement_relationship" do
      series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
      get :edit, {:id => series_statement_relationship.to_param}, valid_session
      assigns(:series_statement_relationship).should eq(series_statement_relationship)
    end
  end

  describe "POST create" do
    login_fixture_librarian

    describe "with valid params" do
      it "creates a new SeriesStatementRelationship" do
        expect {
          post :create, {:series_statement_relationship => valid_attributes}, valid_session
        }.to change(SeriesStatementRelationship, :count).by(1)
      end

      it "assigns a newly created series_statement_relationship as @series_statement_relationship" do
        post :create, {:series_statement_relationship => valid_attributes}, valid_session
        assigns(:series_statement_relationship).should be_a(SeriesStatementRelationship)
        assigns(:series_statement_relationship).should be_persisted
      end

      it "redirects to the created series_statement_relationship" do
        post :create, {:series_statement_relationship => valid_attributes}, valid_session
        response.should redirect_to(SeriesStatementRelationship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved series_statement_relationship as @series_statement_relationship" do
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesStatementRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:series_statement_relationship => {}}, valid_session
        assigns(:series_statement_relationship).should be_a_new(SeriesStatementRelationship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesStatementRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:series_statement_relationship => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    login_fixture_librarian

    describe "with valid params" do
      it "updates the requested series_statement_relationship" do
        series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
        # Assuming there are no other series_statement_relationships in the database, this
        # specifies that the SeriesStatementRelationship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SeriesStatementRelationship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => series_statement_relationship.to_param, :series_statement_relationship => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested series_statement_relationship as @series_statement_relationship" do
        series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
        put :update, {:id => series_statement_relationship.to_param, :series_statement_relationship => valid_attributes}, valid_session
        assigns(:series_statement_relationship).should eq(series_statement_relationship)
      end

      it "redirects to the series_statement_relationship" do
        series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
        put :update, {:id => series_statement_relationship.to_param, :series_statement_relationship => valid_attributes}, valid_session
        response.should redirect_to(series_statement_relationship)
      end
    end

    describe "with invalid params" do
      it "assigns the series_statement_relationship as @series_statement_relationship" do
        series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesStatementRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => series_statement_relationship.to_param, :series_statement_relationship => {}}, valid_session
        assigns(:series_statement_relationship).should eq(series_statement_relationship)
      end

      it "re-renders the 'edit' template" do
        series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesStatementRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => series_statement_relationship.to_param, :series_statement_relationship => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    login_fixture_librarian

    it "destroys the requested series_statement_relationship" do
      series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
      expect {
        delete :destroy, {:id => series_statement_relationship.to_param}, valid_session
      }.to change(SeriesStatementRelationship, :count).by(-1)
    end

    it "redirects to the series_statement_relationships list" do
      series_statement_relationship = FactoryGirl.create(:series_statement_relationship)
      delete :destroy, {:id => series_statement_relationship.to_param}, valid_session
      response.should redirect_to(series_statement_relationships_url)
    end
  end

end
